[package]
name = "atlas-boot-manager"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
build = "build.rs"

[features]
default = ["host"]
host = ["dep:image"]
uefi-app = ["dep:uefi"]

[dependencies]
uefi = { version = "0.41.0", optional = true, features = ["alloc", "global_allocator", "panic_handler", "qemu"] }
image = { version = "0.25.10", optional = true, default-features = false, features = ["png"] }
libm = { version = "0.2.15", default-features = false }

[[bin]]
name = "atlas-boot-host-render"
path = "src/bin/host_render.rs"
required-features = ["host"]

[[bin]]
name = "AtlasBootManager"
path = "src/bin/uefi_main.rs"
required-features = ["uefi-app"]

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true

